### ISSUE TITLE
Fail to install spatial_correlation_sampler

### ISSUE THREAD

**Issue by daeunni** [evalcrafter/EvalCrafter#11]
Hi, I was seeking to run this evaluation code without the docker image you provided. 
However, I got this error when tried to install spatial_correlation_sampler. 
```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for spatial-correlation-sampler
Failed to build spatial-correlation-sampler
ERROR: Could not build wheels for spatial-correlation-sampler, which is required to install pyproject.toml-based projects
```

Is there any way to run this code w/o doker image? Thanks :)

**Comment by Yaofang-Liu** [comment]
> Hi, I was seeking to run this evaluation code without the docker image you provided. 
> 
> However, I got this error when tried to install spatial_correlation_sampler. 
> 
> ```
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> 
>   ERROR: Failed building wheel for spatial-correlation-sampler
> 
> Failed to build spatial-correlation-sampler
> 
> ERROR: Could not build wheels for spatial-correlation-sampler, which is required to install pyproject.toml-based projects
> 
> ```
> 
> 
> 
> Is there any way to run this code w/o doker image? Thanks :) 

Please check this https://github.com/evalcrafter/EvalCrafter/issues/3

**Comment by daeunni** [comment]
Thanks a lot :)
