### ISSUE TITLE
Could you provide VideoCrafter2 Raw metrics? 

### ISSUE THREAD

**Issue by daeunni** [evalcrafter/EvalCrafter#12]
Hi, thanks for your nice work and communication! 
Could you provide VideoCrafter2 raw metrics like below? (Not average per each metric category) Thanks :)  
<img width="1277" alt="image" src="https://github.com/evalcrafter/EvalCrafter/assets/62705839/b9b517da-09a4-4b3a-802f-b9e904df3877">

**Comment by daeunni** [comment]
I already checked [this link](https://huggingface.co/datasets/RaphaelLiu/EvalCrafter_T2V_Dataset/tree/main) which can download generated videos from VideoCrafter2. 

Could you share the exact random seed? 

Since from my side, I cannot reimplement VideoCrafter2's performance with seed 123. I used [this checkpoint](https://huggingface.co/VideoCrafter/VideoCrafter2/blob/main/model.ckpt) from huggingface the author provided.

**Comment by Yaofang-Liu** [comment]
Hi, we used VideoCrafter2 of 640*1024 resolution, and I will upload the corresponding raw metrics later.

**Comment by Yaofang-Liu** [comment]
Please find the raw matric values for VideoCrafter2 [here](https://drive.google.com/drive/folders/1Z5P4N8FpuTSgW7VgOMJpsd4h9Y8YbNxw?usp=sharing
).
