### ISSUE TITLE
Easy Inference code

### ISSUE THREAD

**Issue by Vattikondadheeraj** [evalcrafter/EvalCrafter#14]
Hey, the inference command for this repo is a bit confusing. I dont want to use docker because of some issues in my cluster. But the running manually is a bit confusing. Is there a simple set commands to setup?

**Comment by Yaofang-Liu** [comment]
Many thanks for raising such a good issue. Environment setup with Conda is supported now please check [here ](https://github.com/evalcrafter/EvalCrafter?tab=readme-ov-file#setup-%EF%B8%8F).
