### ISSUE TITLE
Inaccessible Raw Videos Referenced by Alias

### ISSUE THREAD

**Issue by Varchita-Beena** [evalcrafter/EvalCrafter#16]
It appears that the videos are referenced via an alias at /home/ET/liuyaofang/video_evaluation_dataset/zeroscope/0000.mp4. Are the raw videos intended to be uploaded to this location? Currently, they are not accessible. Could you please confirm if there is an alternative path or if these videos will be made available soon?

**Comment by Yaofang-Liu** [comment]
Hi, it's just a soft link operation. You can delete these existing links and create new soft links to your folder that includes those videos. Here's how you can do it:

1. First, remove the existing soft links:

```bash
rm /path/to/your/EvalCrafter/videos/*
```

2. Then, create new soft links to your actual video folder. Assuming your videos are in `/path/to/your/actual/videos/`, you can use this command:

```bash
ln -s /path/to/your/generated/videos/* /path/to/your/EvalCrafter/videos/
```

Replace `/path/to/your/actual/videos/` `/path/to/your/EvalCrafter/videos/` with the actual path in your server.

This script will create soft links for all 700 videos (from 0000.mp4 to 0699.mp4) in the `/path/to/your/EvalCrafter/videos/` directory, pointing to the actual video files in your folder.

After running these commands, the videos should be accessible at the path mentioned in the guidelines, but they'll actually be stored in your own folder.

Do you need any clarification or additional information about this process? Thanks for your interest :-)
