### ISSUE TITLE
 a typo in the 321st prompt

### ISSUE THREAD

**Issue by jidedaka** [evalcrafter/EvalCrafter#2]
There seem to be a typo in the 321st prompt `In 3d game style, Salvador Dal√≠ with a robotic half face`. Right?

**Comment by lajhhzlf** [comment]
And there seem to be a redundant` "style"` in the 285th prompt.

**Comment by lajhhzlf** [comment]
The 100th and 109th prompts are the same.

**Comment by lajhhzlf** [comment]
The 350th prompt appears to have a type `ofA`

**Comment by lajhhzlf** [comment]
The 6th and 19th prompts appear to be the same.

**Comment by lajhhzlf** [comment]
The 257th and 265th prompts appear to have typo "ofTwo"

**Comment by lajhhzlf** [comment]
There are 17 "ofa" typos in the prompt list.

**Comment by vinthony** [comment]
hi, sorry for the inconvenient. It is the first version caused by some style template generation. Fixed.

**Comment by Yaofang-Liu** [comment]
Hi jidedaka, thank you very much for your careful checking. Please ref to the Appendix D. 7 about Benchmark Stability and Noise Variables analysis in our updated paper https://arxiv.org/html/2310.11440v3, which shows that these typos has subtle effects on our benchmark. For the sake of convenience, we kept this small amount of noise in our current version. 
Please feel free to ask any further questions. Many thanks!
