### ISSUE TITLE
Cannnot download Warping Error module

### ISSUE THREAD

**Issue by HanLiii** [evalcrafter/EvalCrafter#20]
gdown --id "1hF8vS6YeHkx3j2pfCeQqqZGwA_PJq_Da"
/data/hli358/envs/evalcrafter/lib/python3.10/site-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
/data/hli358/envs/evalcrafter/lib/python3.10/site-packages/gdown/download.py:33: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = bs4.BeautifulSoup(line, features="html.parser")
Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.
        Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=1hF8vS6YeHkx3j2pfCeQqqZGwA_PJq_Da

but Gdown can't. Please check connections and permissions.

**Comment by Yaofang-Liu** [comment]
Hi, this is an alternative to download that file: https://huggingface.co/RaphaelLiu/EvalCrafter-Models/tree/main
