### ISSUE TITLE
About EvalCrafter Env

### ISSUE THREAD

**Issue by fjscfy** [evalcrafter/EvalCrafter#3]
Hello, I'd like to ask if it's possible to run your code metrics without using Docker, or could you share the requirements.txt for your environment?

**Comment by Yaofang-Liu** [comment]
Thanks for your suggestion, we're working on it.

**Comment by daeunni** [comment]
@Yaofang-Liu May I ask are there updates? thanks :)

**Comment by Yaofang-Liu** [comment]
We tried to do so, but it seems that there are too many packages, which cause many incompatible issues when using Conda or pip for installation. I will upload the requirements.txt right away and take a deep dive into it later.
 
Feel free to let me know if you have any good suggestions. Many thanks :-)

**Comment by Yaofang-Liu** [comment]
Now, you could consider using `requirements.txt` or `environment.yml` to set up the environment.

**Comment by Edwardyan1112** [comment]
> Now, you could consider using `requirements.txt` or `environment.yml` to set up the environment.

I am using `requirements.txt` and `environment.yml` to build environment, but I found there are many package version conflict. Is there any way to update the correct requirements?

**Comment by Yaofang-Liu** [comment]
> > Now, you could consider using `requirements.txt` or `environment.yml` to set up the environment.
> 
> I am using `requirements.txt` and `environment.yml` to build environment, but I found there are many package version conflict. Is there any way to update the correct requirements?

Many thanks for raising such a good issue. Environment setup with Conda is supported now please check [here ](https://github.com/evalcrafter/EvalCrafter?tab=readme-ov-file#setup-%EF%B8%8F).

**Comment by Edwardyan1112** [comment]
> > > Now, you could consider using `requirements.txt` or `environment.yml` to set up the environment.
> > 
> > 
> > I am using `requirements.txt` and `environment.yml` to build environment, but I found there are many package version conflict. Is there any way to update the correct requirements?
> 
> Many thanks for raising such a good issue. Environment setup with Conda is supported now please check [here ](https://github.com/evalcrafter/EvalCrafter?tab=readme-ov-file#setup-%EF%B8%8F).

Thanks for reply. But there are still many conflicts in environment.yml. For example:
> The conflict is caused by:                                                                                                      
> The user requested keras==2.13.1                                                                                             
> tensorflow 2.12.0 depends on keras<2.13 and >=2.12.0

**Comment by Yaofang-Liu** [comment]
> > > > Now, you could consider using `requirements.txt` or `environment.yml` to set up the environment.
> > > 
> > > 
> > > I am using `requirements.txt` and `environment.yml` to build environment, but I found there are many package version conflict. Is there any way to update the correct requirements?
> > 
> > 
> > Many thanks for raising such a good issue. Environment setup with Conda is supported now please check [here ](https://github.com/evalcrafter/EvalCrafter?tab=readme-ov-file#setup-%EF%B8%8F).
> 
> Thanks for reply. But there are still many conflicts in environment.yml. For example:
> 
> > The conflict is caused by:
> > The user requested keras==2.13.1
> > tensorflow 2.12.0 depends on keras<2.13 and >=2.12.0

It should be okay now. Many thanks for raising this issue!
