### ISSUE TITLE
Will the human annotation for computing correlation with human judgements be released?

### ISSUE THREAD

**Issue by linzhiqiu** [evalcrafter/EvalCrafter#4]
I wonder if it is possible to release the data for Table 4 in main paper. Thanks!

**Comment by Yaofang-Liu** [comment]
Hi linzhiqiu, We just released the [Human Feedback](https://drive.google.com/file/d/1hbSoGoqD6DO2yV2R6wn8NKvK0nUxMDqv/view?usp=sharing), which includes _**8.6k feedback**_, covers _**5 aspects**_ like visual quality and t2v alignment! ！
Please check. Many thanks for your notice!
