### ISSUE TITLE
Clarification on Dataset Videos

### ISSUE THREAD

**Issue by PR-Ryan** [evalcrafter/EvalCrafter#5]
Thank you for your work and for sharing the dataset. I've noticed that the videos within the modelscope and zeroscope categories contain the Pika Labs watermark. Could this indicate an issue with the uploaded versions of these videos?

Additionally, I am curious about the relationship between the 700 prompts mentioned in your dataset release and the 500 prompts discussed in your paper. Could you clarify how these sets of prompts relate to each other?

Looking forward to your clarification. Thanks for your time and effort on this project.

**Comment by Yaofang-Liu** [comment]
Thanks for raising such good questions and sorry for the misleading! 

- The watermarks within the videos are introduced during our user study stage. We add Pika's watermarks to other methods to reduce user bias on different methods. These watermarks have marginal influence on the evaluation results from our observation.

- The discrepancy between 700 and 500 prompts arose from our endeavors to continuously update and enhance our prompt
list. Our initial benchmark contains 512 prompts for user study, and we further expanded it to 700 prompts to make it more comprehensive and balanced. However, there are no significant changes in our results after the prompt increment from our experiments. Therefore, we use the same user study result to avoid wasting resources as the initial version. Besides, we will release the updated version of our paper soon.

Please reach out if you have any further questions. Thanks :-)

**Comment by PR-Ryan** [comment]
Thank you for the clarification and taking the time to respond. Your explanation has helped me understand the matter better. With my questions now answered, I will close this issue.
