### ISSUE TITLE
Motion quality and Visual quality columns are swapped

### ISSUE THREAD

**Issue by zeinsh** [evalcrafter/EvalCrafter#8]
Hi! I tried to reproduce the final scores in your benchmark using [eval_from_metrics.py](https://github.com/evalcrafter/EvalCrafter/blob/master/eval_from_metrics.py) starting from raw metrics.

I noticed that you swapped the numbers in motion quality and visual quality in https://evalcrafter.github.io and https://huggingface.co/spaces/AILab-CVC/EvalCrafter.

Am I correct?

**Comment by Yaofang-Liu** [comment]
Yes, you're correct. It's our mistake. Many thanks for pointing out the problem! We will fix this right away.
